---
- name: Install ara
  pip:
    name: ara[server]
  notify: restart ara-api

- name: Setup Ara config file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'ara.cfg', dest: '/root/.ara/server/settings.yaml' }

- name: Restart supervisor ara project
  ansible.builtin.command:
    cmd: supervisorctl restart ara

- name: Apply Ara DB migrations
  ansible.builtin.command:
    cmd: ara-manage migrate
