---
- name: Remove vim-common and vim-tiny
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - vim-tiny

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ packages }}"

- name: Upgrade ansible on guest
  pip:
    name: 'ansible>2.9.6'
    state: present

- name: Set Bashrc
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'bashrc', dest: '/root/.bashrc' }
    - { src: 'bashrc', dest: '/home/antonio/.bashrc' }
    - { src: 'bashrc', dest: '/home/lucas/.bashrc' }

- name: Create src
  file:
    path: /src
    owner: antonio
    group: antonio
    state: directory

#- name: Install Ara Server
#  include_tasks: ara.yml
#  when: inventory_hostname in groups['ara-server']

#- name: Import Supervisor
#  include_tasks: supervisor.yml
#  when: inventory_hostname in groups['supervisor']

#- name: Set Backup Solution
#  include_tasks: urbackup.yaml
#  when: inventory_hostname in groups['urbackup']
