---
- name: Install Supervisord
  pip:
    name: supervisor
    state: present
    executable: pip3
  become: "yes"

- name: Create src
  file:
    path: /etc/supervisor
    owner: root
    group: root
    state: directory

- name: Setup Supervisor config file for node_exporter
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'supervisord_node_exporter.conf', dest: '/etc/supervisor/supervisord.conf' }

- name: Start reload
  ansible.builtin.command:
    cmd: supervisorctl reread
  ignore_errors: true

- name: Start update
  ansible.builtin.command:
    cmd: supervisorctl update
  ignore_errors: true

- name: Start Supervisor
  ansible.builtin.command:
    cmd: supervisord -c /etc/supervisor/supervisord.conf
  ignore_errors: true
