---
- name: Install backup clientpackages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ backup_solutionL }}"

- name: Add urbackup stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:uroni/urbackup
  when: inventory_hostname in groups['urbackup-server']

- name: Install urbackup server
  ansible.builtin.apt:
    name: urbackup-server
    state: "present"
  when: inventory_hostname in groups['urbackup-server']

#- name: Setup admin ui password
#  ansible.builtin.shell: urbackupsrv reset-admin-pw --admin-user urbackup -p "{{ urbackup_admin }}

- name: Download urbackup Client
  ansible.builtin.get_url:
    url: https://hndl.urbackup.org/Client/2.5.24/urbackup-client-2.5.24.tar.gz
    dest: /tmp/urbackup-client-2.5.24.tar.gz
    mode: '0440'

- name: Unpack urbackup client
  ansible.builtin.unarchive:
    src: /tmp/urbackup-client-2.5.24.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Execute urbackup-client-2.5.24 Config
  ansible.builtin.shell: /bin/bash configure --enable-headless
  args:
    chdir: /tmp/urbackup-client-2.5.24.0/

- name: Execute make j4
  ansible.builtin.command: make -j4
  args:
    chdir:  /tmp/urbackup-client-2.5.24.0/

- name: Execute make install
  ansible.builtin.command: make install
  args:
    chdir: /tmp/urbackup-client-2.5.24.0/

- name: Remove tar
  ansible.builtin.command:  rm -rf /tmp/urbackup-client-2.5.24.tar.gz