---
- name: Set haproxy config
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'haproxy.cfg', dest: '/etc/haproxy/haproxy.cfg' }

- name: Restart service haproxy, in all cases
  ansible.builtin.service:
    name: haproxy
    state: restarted