---
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: install hashicorp Terraform repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    state: present
  become: true

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: apt_key_output

- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
  when: apt_key_output.state is not defined

- name: Create src
  file:
    path: /src
    owner: antonio
    group: antonio
    state: directory

- name: Clone Terraform-KLVM
  become: yes
  become_user: antonio
  ansible.builtin.git:
    repo: https://gitlab.com/ammartins/terraform-kvm.git
    dest: /src/terraform-kvm
    force: yes

- name: Install terraform cluster packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ terraform_packages }}"

- name: Configure Clusteer Mega
  include_tasks: k8s-cluster-mega.yml
  when: inventory_hostname in groups['k8s-mega']