---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ammartins/ansible:64
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ~/.vault_password
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
