---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - php8.1-cgi
    - php8.1
    - nginx

- name: Get Install for NextClopud
  ansible.builtin.get_url:
    url: https://download.nextcloud.com/server/releases/latest.tar.bz2
    dest: /backups
    force_basic_auth: yes

- name: Extract nexcloud
  ansible.builtin.unarchive:
    src: latest.tar.bz2
    dest: /backups

- name: Install PHP Missing Package
  apt:
    name: "{{ item }}"
    state: "present"
  white_items:
    - php8.1-curl
    - php8.1-dom
    - php8.1-GD
    - php8.1-JSON
    - php8.1-mbstring
    - php8.1-SimpleXML
    - php8.1-XMLReader
    - php8.1-XMLWriter
    - php8.1-zip
    - php8.1-mysql