---
- name: Set haproxy config
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'haproxy-bulky.cfg', dest: '/etc/haproxy/haproxy.cfg' }

- name: Restart service haproxy, in all cases
  ansible.builtin.service:
    name: haproxy
    state: restarted

#- name: Set Kubectl autocomplete
#  become_user: kube
#  shell: echo 'source <(kubectl completion bash)' >>~/.bashrc
#
#- name: Set Alias kubectl
#  become_user: kube
#  shell: echo 'alias k=kubectl' >>~/.bashrc
#
#- name: Set Alias kubectl autocomplete
#  become_user: kube
#  shell: echo 'complete -F __start_kubectl k' >>~/.bashrc