---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - mysql-server
    - python3-pymysql

- name: Set a hostname for all nodes
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Edit hosts file on server
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ inventory_hostname }}$'
    line: "127.0.0.1 {{inventory_hostname}}"
    state: present

- name: Create
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    priv: '*.*:ALL'
    host: "{{ mysql_host | default('%') }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: Push MySQL user pass to vault using KV v2
  uri:
    url: "{{ vault_addr }}/v1/ansible-managed/data/mysql"
    method: POST
    headers:
      X-Vault-Token: "{{ vault_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      data:
        username: "{{ mysql_user }}"
        password: "{{ mysql_pass }}"

