- name: Update Machines
  hosts: 'all-machines'
  connection: ssh
  gather_facts: "False"
  user: root
  max_fail_percentage: 0
  tags: update
  roles:
    - { role: playbooks/update }

- name: Initial Machine Setup
  hosts: 'all-machines'
  connection: ssh
  gather_facts: "False"
  user: root
  tags: init
  max_fail_percentage: 0
  roles:
    - { role: playbooks/base }


- name: Setup / Update Nexcloud
  hosts: 'nextcloud-server'
  connection: ssh
  gather_facts: "False"
  user: root
  tags: nextcloud
  max_fail_percentage: 0
  roles:
    - { role: playbooks/nextcloud }

- name: Setup / Update MySql
  hosts: 'mysql-servers'
  connection: ssh
  gather_facts: "False"
  user: root
  tags: mysql
  max_fail_percentage: 0
  roles:
    - { role: playbooks/mysql }

#- name: Setup Youtrack MyD2
#  hosts: 'youtrack-server'
#  connection: ssh
#  gather_facts: "False"
#  user: root
#  tags: youtrack
#  max_fail_percentage: 0
#  roles:
#    - { role: playbooks/youtrack }
