- name: Setup / Update Postgresql
  hosts: 'postgresql-servers'
  connection: ssh
  gather_facts: "False"
  user: root
  tags: psql
  max_fail_percentage: 0
  vars_files:
    - ../group_vars/all/all-cluster.yaml
  roles:
    - { role: roles/psql-cluster }